routes/admin.php
<?php


/*
|--------------------------------------------------------------------------
| Admin Auth Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 			'AdminController@dashboard')->name('index');
Route::get('/dashboard', 	'AdminController@dashboard')->name('dashboard');
Route::get('/translation', 	'AdminController@translation')->name('translation');

Route::resource('user', 	'Resource\UserResource');
Route::resource('document', 'Resource\DocumentResource');

Route::resource('promocode','Resource\PromocodeResource');

Route::group(['as' => 'provider.'], function () {
    Route::get('review/provider', 'AdminController@provider_review')->name('review');
    Route::get('provider/{id}/approve', 'Resource\ProviderResource@approve')->name('approve');
    Route::get('provider/{id}/disapprove', 'Resource\ProviderResource@disapprove')->name('disapprove');
    Route::get('provider/{id}/request', 'Resource\ProviderResource@request')->name('request');
    Route::resource('provider/{provider}/document', 'Resource\ProviderDocumentResource');
    Route::get('provider/{id}/statement', 'Resource\ProviderResource@statement')->name('statement');

});

Route::get('setting', 				'AdminController@setting')->name('setting');
Route::post('setting/store', 		'AdminController@setting_store')->name('setting.store');
Route::get('profile', 				'AdminController@profile')->name('profile');
Route::post('profile/update', 		'AdminController@profile_update')->name('profile.update');
Route::get('password', 				'AdminController@password')->name('password');
Route::post('password/update', 		'AdminController@password_update')->name('password.update');
Route::get('payment', 				'AdminController@payment')->name('payment');
Route::get('payment/setting', 		'AdminController@payment_setting')->name('payment.setting');
Route::post('payment/setting', 'AdminController@settings_payment_store')->name('settings.payment.store');
Route::get('help', 					'AdminController@help')->name('help');
Route::get('/privacy', 				'AdminController@privacy')->name('privacy');
Route::post('/pages', 				'AdminController@pages')->name('pages.update');

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Authentication Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::group(['prefix' => 'admin'], function () {
    Route::get('/login', 'AdminAuth\LoginController@showLoginForm');
    Route::post('/login', 'AdminAuth\LoginController@login');
    Route::post('/logout', 'AdminAuth\LoginController@logout');

    Route::post('/password/email', 'AdminAuth\ForgotPasswordController@sendResetLinkEmail');
    Route::post('/password/reset', 'AdminAuth\ResetPasswordController@reset');
    Route::get('/password/reset', 'AdminAuth\ForgotPasswordController@showLinkRequestForm');
    Route::get('/password/reset/{token}', 'AdminAuth\ResetPasswordController@showResetForm');
});

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', 'UserController@index');

Auth::routes();

Route::get('privacy', function () {
    $page = 'page_privacy';
    $title = 'Privacy Policy';
    return view('static', compact('page', 'title'));
});


/*
|--------------------------------------------------------------------------
| User Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/dashboard', 'UserController@dashboard');

// user profiles
Route::get('/profile',      'HomeController@profile');
Route::get('/edit/profile', 'HomeController@edit_profile');
Route::post('/profile',     'HomeController@update_profile');

// update password
Route::get('/change/password',  'HomeController@change_password');
Route::post('/change/password', 'HomeController@update_password');

Route::group(['prefix' => 'celebrity'], function () {
  Route::get('/login', 'CelebrityAuth\LoginController@showLoginForm')->name('login');
  Route::post('/login', 'CelebrityAuth\LoginController@login');
  Route::post('/logout', 'CelebrityAuth\LoginController@logout')->name('logout');

  Route::get('/register', 'CelebrityAuth\RegisterController@showRegistrationForm')->name('register');
  Route::post('/register', 'CelebrityAuth\RegisterController@register');

  Route::post('/password/email', 'CelebrityAuth\ForgotPasswordController@sendResetLinkEmail')->name('password.request');
  Route::post('/password/reset', 'CelebrityAuth\ResetPasswordController@reset')->name('password.email');
  Route::get('/password/reset', 'CelebrityAuth\ForgotPasswordController@showLinkRequestForm')->name('password.reset');
  Route::get('/password/reset/{token}', 'CelebrityAuth\ResetPasswordController@showResetForm');
});

resources/views/admin/include/footer.blade.php
<!-- Footer -->
<footer class="footer">
	<div class="container-fluid">
		<div class="row text-xs-center">
			<div class="col-sm-4 text-sm-left mb-0-5 mb-sm-0">
				{{date('Y')}} © {{Setting::get('site_title','Kifiya')}}
			</div>
		</div>
	</div>
</footer>

resources/views/admin/include/header.blade.php
<!-- Header -->
<div class="site-header">
	<nav class="navbar navbar-light">
		<div class="navbar-left">
			<a class="navbar-brand" href="{{url('admin/dashboard')}}">
				<?php $site_logo = Setting::get('site_logo'); ?>
				<div class="logo" style="background: url({{$site_logo}}) no-repeat;background-size: contain;filter: invert(100%);"></div>
			</a>
			<div class="toggle-button dark sidebar-toggle-first float-xs-left hidden-md-up">
				<span class="hamburger"></span>
			</div>
			<div class="toggle-button-second dark float-xs-right hidden-md-up">
				<i class="ti-arrow-left"></i>
			</div>
			<div class="toggle-button dark float-xs-right hidden-md-up" data-toggle="collapse" data-target="#collapse-1">
				<span class="more"></span>
			</div>
		</div>
		<div class="navbar-right navbar-toggleable-sm collapse" id="collapse-1">
			<div class="toggle-button light sidebar-toggle-second float-xs-left hidden-sm-down">
				<span class="hamburger"></span>
			</div>

			<ul class="nav navbar-nav">
				<li class="nav-item hidden-sm-down">
					<a class="nav-link toggle-fullscreen" href="#">
						<i class="ti-fullscreen"></i>
					</a>
				</li>
			</ul>
			
			<ul class="nav navbar-nav float-md-right">
				<li class="nav-item dropdown hidden-sm-down">
					<a href="#" data-toggle="dropdown" aria-expanded="false">
						<span class="avatar box-32">
							<img src="{{img(Auth::guard('admin')->user()->picture)}}" alt="">
						</span>
					</a>
					<div class="dropdown-menu dropdown-menu-right animated fadeInUp">
						<a class="dropdown-item" href="{{route('admin.profile')}}">
							<i class="ti-user mr-0-5"></i> Profile
						</a>
						<a class="dropdown-item" href="{{route('admin.password')}}">
							<i class="ti-settings mr-0-5"></i> Change Password
						</a>
						<div class="dropdown-divider"></div>
						<a class="dropdown-item" href="{{route('admin.help')}}"><i class="ti-help mr-0-5"></i> Help</a>
						<a class="dropdown-item" href="{{ url('/admin/logout') }}"
                            onclick="event.preventDefault();
                                     document.getElementById('logout-form').submit();"><i class="ti-power-off mr-0-5"></i> Sign out</a>
                         <form id="logout-form" action="{{ url('/admin/logout') }}" method="POST" style="display: none;">
                    			{{ csrf_field() }}
                		</form>
					</div>
				</li>
			</ul>

		</div>
	</nav>
</div>

resources/views/admin/include/nav.blade.php
<div class="site-sidebar">
	<div class="custom-scroll custom-scroll-light">
		<ul class="sidebar-menu">
			<li class="menu-title">Main</li>
			<li>
				<a href="{{route('admin.dashboard')}}" class="waves-effect  waves-light">
					<span class="s-icon"><i class="ti-anchor"></i></span>
					<span class="s-text">Dashboard</span>
				</a>
			</li>
			<li>
				<a href="{{ route('admin.dispatcher.trips') }}" class="waves-effect waves-light">
					<span class="s-icon"><i class="ti-target"></i></span>
					<span class="s-text">Dispatcher Panel</span>
				</a>
			</li>
			
			<li class="menu-title">Members</li>
			<li class="with-sub">
				<a href="#" class="waves-effect  waves-light">
					<span class="s-caret"><i class="fa fa-angle-down"></i></span>
					<span class="s-icon"><i class="ti-crown"></i></span>
					<span class="s-text">Users</span>
				</a>
				<ul>
					<li><a href="{{route('admin.user.index')}}">List Users</a></li>
					<li><a href="{{route('admin.user.create')}}">Add New</a></li>
				</ul>
			</li>
			<li class="with-sub">
				<a href="#" class="waves-effect  waves-light">
					<span class="s-caret"><i class="fa fa-angle-down"></i></span>
					<span class="s-icon"><i class="ti-car"></i></span>
					<span class="s-text">@lang('main.provider')s</span>
				</a>
				<ul>
					<li><a href="{{route('admin.provider.index')}}">List Partners</a></li>
					<li><a href="{{route('admin.provider.create')}}">Add New</a></li>
				</ul>
			</li>
			<li class="menu-title">Details</li>
			<li class="with-sub">
				<a href="#" class="waves-effect  waves-light">
					<span class="s-caret"><i class="fa fa-angle-down"></i></span>
					<span class="s-icon"><i class="ti-map-alt"></i></span>
					<span class="s-text">Map</span>
				</a>
				<ul>
					<li><a href="{{route('admin.user.map')}}">User Locations</a></li>
					<li><a href="{{route('admin.provider.map')}}">Partner Locations</a></li>
				</ul>
			</li>
			<li class="with-sub">
				<a href="#" class="waves-effect  waves-light">
					<span class="s-caret"><i class="fa fa-angle-down"></i></span>
					<span class="s-icon"><i class="ti-view-grid"></i></span>
					<span class="s-text">Ratings & Reviews</span>
				</a>
				<ul>
					<li><a href="{{route('admin.user.review')}}">User Ratings</a></li>
					<li><a href="{{route('admin.provider.review')}}">Partner Ratings</a></li>
				</ul>
			</li>
			<li class="menu-title">@lang('main.service')s</li>
			<li>
				<a href="{{route('admin.request.history')}}" class="waves-effect  waves-light">
					<span class="s-icon"><i class="ti-infinite"></i></span>
					<span class="s-text">@lang('main.service')s History</span>
				</a>
			</li>
			<li>
				<a href="{{route('admin.scheduled.request')}}" class="waves-effect  waves-light">
					<span class="s-icon"><i class="ti-palette"></i></span>
					<span class="s-text">Scheduled Services</span>
				</a>
			</li>
			<li class="menu-title">General</li>
			<li class="with-sub">
				<a href="#" class="waves-effect  waves-light">
					<span class="s-caret"><i class="fa fa-angle-down"></i></span>
					<span class="s-icon"><i class="ti-view-grid"></i></span>
					<span class="s-text">Categories</span>
				</a>
				<ul>
					<li><a href="{{route('admin.category.index')}}">List Category</a></li>
					<li><a href="{{route('admin.category.create')}}">Add New Category</a></li>
				</ul>
			</li>
			<li class="with-sub">
				<a href="#" class="waves-effect  waves-light">
					<span class="s-caret"><i class="fa fa-angle-down"></i></span>
					<span class="s-icon"><i class="ti-view-grid"></i></span>
					<span class="s-text">Service Types</span>
				</a>
				<ul>
					<li><a href="{{route('admin.service.index')}}">List Service Types</a></li>
					<li><a href="{{route('admin.service.create')}}">Add New Service Type</a></li>
				</ul>
			</li>
			<li class="with-sub">
				<a href="#" class="waves-effect  waves-light">
					<span class="s-caret"><i class="fa fa-angle-down"></i></span>
					<span class="s-icon"><i class="ti-view-grid"></i></span>
					<span class="s-text">Service Sub Categories</span>
				</a>
				<ul>
					<li><a href="{{route('admin.service-sub-category.index')}}">List Service Sub Category</a></li>
					<li><a href="{{route('admin.service-sub-category.create')}}">Add New Service Sub Category</a></li>
				</ul>
			</li>


			<li class="menu-title">Accounts</li>
			<li class="with-sub">
				<a href="#" class="waves-effect  waves-light">
					<span class="s-caret"><i class="fa fa-angle-down"></i></span>
					<span class="s-icon"><i class="ti-crown"></i></span>
					<span class="s-text">Statements</span>
				</a>
				<ul>
					<li><a href="{{ route('admin.ride.statement') }}">Overall @lang('main.service') Statements</a></li>
					<li><a href="{{ route('admin.ride.statement.provider') }}">@lang('main.provider') Statement</a></li>
					<li><a href="{{ route('admin.ride.statement.today') }}">Daily Statement</a></li>
					<li><a href="{{ route('admin.ride.statement.monthly') }}">Monthly Statement</a></li>
					<li><a href="{{ route('admin.ride.statement.yearly') }}">Yearly Statement</a></li>
				</ul>
			</li>
			
			<li class="with-sub">
				<a href="#" class="waves-effect  waves-light">
					<span class="s-caret"><i class="fa fa-angle-down"></i></span>
					<span class="s-icon"><i class="ti-layout-tab"></i></span>
					<span class="s-text">Promocodes</span>
				</a>
				<ul>
					<li><a href="{{route('admin.promocode.index')}}">List Promocodes</a></li>
					<li><a href="{{route('admin.promocode.create')}}">Add New Promocode</a></li>
				</ul>
			</li>

			<li class="with-sub">
				<a href="#" class="waves-effect  waves-light">
					<span class="s-caret"><i class="fa fa-angle-down"></i></span>
					<span class="s-icon"><i class="ti-layout-tab"></i></span>
					<span class="s-text">Documents</span>
				</a>
				<ul>
					<li><a href="{{route('admin.document.index')}}">List Documents</a></li>
					<li><a href="{{route('admin.document.create')}}">Add New </a></li>
				</ul>
			</li>
			
			<li class="menu-title">Payment Details</li>
			<li>
				<a href="{{route('admin.payment')}}" class="waves-effect  waves-light">
					<span class="s-icon"><i class="ti-infinite"></i></span>
					<span class="s-text">Payment History</span>
				</a>
			</li>
			<li>
				<a href="{{route('admin.payment.setting')}}" class="waves-effect  waves-light">
					<span class="s-icon"><i class="ti-money"></i></span>
					<span class="s-text">Payment Settings</span>
				</a>
			</li>
			<li class="menu-title">Settings</li>
			<li>
				<a href="{{route('admin.setting')}}" class="waves-effect  waves-light">
					<span class="s-icon"><i class="ti-settings"></i></span>
					<span class="s-text">Site Settings</span>
				</a>
			</li>
			
			<li class="menu-title">Others</li>
			<li>
				<a href="{{route('admin.help')}}" class="waves-effect waves-light">
					<span class="s-icon"><i class="ti-help"></i></span>
					<span class="s-text">Help</span>
				</a>
			</li>
			<li>
				<a href="{{route('admin.translation')}}" class="waves-effect waves-light">
					<span class="s-icon"><i class="ti-smallcap"></i></span>
					<span class="s-text">Translations</span>
				</a>
			</li>
			<li class="menu-title">Account</li>
			<li>
				<a href="{{route('admin.profile')}}" class="waves-effect  waves-light">
					<span class="s-icon"><i class="ti-user"></i></span>
					<span class="s-text">Account Settings</span>
				</a>
			</li>
			<li>
				<a href="{{route('admin.password')}}" class="waves-effect  waves-light">
					<span class="s-icon"><i class="ti-exchange-vertical"></i></span>
					<span class="s-text">Change Password</span>
				</a>
			</li>
			<li class="compact-hide">
				<a href="{{ url('/admin/logout') }}"
                            onclick="event.preventDefault();
                                     document.getElementById('logout-form').submit();">
					<span class="s-icon"><i class="ti-power-off"></i></span>
					<span class="s-text">Logout</span>
                </a>

                <form id="logout-form" action="{{ url('/admin/logout') }}" method="POST" style="display: none;">
                    {{ csrf_field() }}
                </form>
			</li>
			
		</ul>
	</div>
</div>